### ISSUE TITLE
Lab Report 2 Feedback

### ISSUE THREAD

**Issue by enzohnnn** [jhugomagana/cse15l-lab-reports#2]
**Bug/Input 1**
- [x] Commit screenshot for bug/input 1
- [x] Link to test file for bug/input 1
- [x] Symptom shown as command + output for bug/input 1
- [x] Description of relationship between bug, symptom, and input for bug/input 1

**Bug/Input 2**
- [x] Commit screenshot for bug/input 2
- [x] Link to test file for bug/input 2
- [x] Symptom shown as command + output for bug/input 2
- [x] Description of relationship between bug, symptom, and input for bug/input 2

**Bug/Input 3**
- [x] Commit screenshot for bug/input 3
- [x] Link to test file for bug/input 3
- [x] Symptom shown as command + output for bug/input 3
- [x] Description of relationship between bug, symptom, and input for bug/input 3

Additional comments from your grader:
I'm really sorry but it looks like you went really above and beyond with parts of your lab submission with the long intro, the inclusion of background music, and more. However, the main parts we were looking to grade don't seem to show up anywhere. Your bugfix #2 and #3 are completely blank and your bug fix #1 is a video of you demonstrating the fix, running the command, etc but that wasn't what we were looking for. 

Unfortunately, reading the rubric I don't think I can award any points for this. You will have a chance to get back points in the regrade request but for your next report, I think your time is better spent trying to follow what the write-up was telling you to include in the report rather than include a bunch of extraneous stuff while not including any part of what we wanted. Best wishes to you and good luck.

Feel free to comment below if you have any questions about the rubric/feedback.

**Comment by jhugomagana** [comment]
@enzohnnn ok thank you, was absent during lab 4 and was trying to catch up to have more examples
For the regrade - do i post both the updated webpage link and the link this thread?

**Comment by enzohnnn** [comment]
Good job with the fixes. If you are ever absent and need help catching up then if you have time, try attending our tutor help hours!
